// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALUJ22BE7bZ1C49hh8B1RLWSUk5B7IjUQ',
    appId: '1:159057073825:web:efdc2a1fcde9cd491982e0',
    messagingSenderId: '159057073825',
    projectId: 'test-pos-2aeb8',
    authDomain: 'test-pos-2aeb8.firebaseapp.com',
    storageBucket: 'test-pos-2aeb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJgmY-xiWGjwPE1CyYMn7mnRi_QZFnrgo',
    appId: '1:159057073825:android:08bb2b9a3a8c53951982e0',
    messagingSenderId: '159057073825',
    projectId: 'test-pos-2aeb8',
    storageBucket: 'test-pos-2aeb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5_TOcsx2918hLPQW8XzQ5kEWuabjtz6I',
    appId: '1:159057073825:ios:7a138c6075b1651b1982e0',
    messagingSenderId: '159057073825',
    projectId: 'test-pos-2aeb8',
    storageBucket: 'test-pos-2aeb8.appspot.com',
    iosClientId:
        '159057073825-t6jj4qbasa2tpfja3ajamdvs6bujacu7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksapos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5_TOcsx2918hLPQW8XzQ5kEWuabjtz6I',
    appId: '1:159057073825:ios:2a47243f3e02e3371982e0',
    messagingSenderId: '159057073825',
    projectId: 'test-pos-2aeb8',
    storageBucket: 'test-pos-2aeb8.appspot.com',
    iosClientId:
        '159057073825-ioeh41o31l2bp0i7db1jmu3es36qbi0q.apps.googleusercontent.com',
    iosBundleId: 'com.firstlogicmetalab.pizzaRomiPosNew.RunnerTests',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALUJ22BE7bZ1C49hh8B1RLWSUk5B7IjUQ',
    appId: '1:159057073825:web:efdc2a1fcde9cd491982e0',
    messagingSenderId: '159057073825',
    projectId: 'test-pos-2aeb8',
    authDomain: 'test-pos-2aeb8.firebaseapp.com',
    storageBucket: 'test-pos-2aeb8.appspot.com',
  );
}
